const GET_PROFILE_USER = 'GET_PROFILE_USER'
const POST_MOOD = 'POST_MOOD'
const GET_USER_MOODS = 'GET_USER_MOODS'
const USER_ERROR = 'USER_ERROR'

export {
    GET_PROFILE_USER,
    POST_MOOD,
    GET_USER_MOODS,
    USER_ERROR
}